Repository baloise/design-system, pull requests merged in 2020-10, with the labels that each got.

#162 fix navbar mobile menu toggle and styling
  src/components/navbar/navbar.tsx
  src/components/navbar/readme.md
  src/scss/components/navbar.scss
  src/scss/elements/input.scss
Labels: bug, help wanted, styling

#163 feat(card-steps): it is possible to disable the navigation
  src/components.d.ts
  src/components/card-steps/card-steps.tsx
  src/components/card-steps/readme.md
Labels: enhancement

#164 fix(dropdown): change placeholder color for inverted style
  src/components/card-steps/readme.md
  src/components/dropdown/dropdown.scss
  src/components/dropdown/readme.md
Labels: styling

#165 feat(typography): improve typography #158
  src/_sidebar.md
  src/docs/elements/title.md
  src/docs/essentials/typography.md
  src/scss/base/_all.scss
  src/scss/base/typography.scss
Labels: enhancement
