Repository baloise/design-system, pull requests merged in 2020-04, with the labels that each got.

#101 fix(npm): fix vulnerabilities of minimist
  package.json
Labels: bug

#103 fix(npm): update deps patch versions
  package-lock.json
  package.json
Labels: dependencies

#109 docs: update npm and index.html description
  package.json
  src/index.html
Labels: documentation

#107 feat(footer): Add footer element
  src/_sidebar.md
  src/docs/elements/footer.md
  src/scss/elements/_all.scss
  src/scss/elements/footer.scss
Labels: enhancement

#83 feat(datetimepicker): Implement basic datetimepicker
  src/_sidebar.md
  src/components.d.ts
  src/components/button/readme.md
  src/components/datepicker/datepicker.tsx
  src/components/datepicker/readme.md
  src/components/datetimepicker/datetimepicker.scss
  src/components/datetimepicker/datetimepicker.tsx
  src/components/datetimepicker/readme.md
  src/components/dropdown/dropdown.tsx
  src/components/dropdown/readme.md
  src/components/icon/bal-icons.scss
  src/components/icon/icon.tsx
  src/components/icon/readme.md
  src/components/timeinput/readme.md
  src/components/timeinput/timeinput.scss
  src/components/timeinput/timeinput.tsx
Labels: enhancement

#115 chore(lint): replace tslint with eslint
  .eslintrc.js
  package-lock.json
  package.json
  src/components/datepicker/i18n.ts
  tslint.json
Labels: enhancement

#117 feat(hint): add new component hint
  .eslintrc.js
  .prettierrc
  src/_sidebar.md
  src/components.d.ts
  src/components/button/readme.md
  src/components/field/field.scss
  src/components/field/field.tsx
  src/components/hint-text/hint-text.scss
  src/components/hint-text/hint-text.tsx
  src/components/hint-text/readme.md
  src/components/hint-title/hint-title.scss
  src/components/hint-title/hint-title.tsx
  src/components/hint-title/readme.md
  src/components/hint/hint.scss
  src/components/hint/hint.tsx
  src/components/hint/readme.md
  src/components/icon/readme.md
  src/docs/assets/styles/styles.css
  src/scss/elements/input.scss
Labels: enhancement

#118 Feat/filter
  .eslintignore
  package-lock.json
  package.json
  server.js
  src/_sidebar.md
  src/components.d.ts
  src/components/button/button.scss
  src/components/button/button.tsx
  src/components/button/readme.md
  src/components/filter-button/filter-button.scss
  src/components/filter-button/filter-button.tsx
  src/components/filter-button/readme.md
  src/components/icon/icon.scss
  src/components/list-item-content/list-item-content.scss
  src/components/list-item-content/list-item-content.tsx
  src/components/list-item-content/readme.md
  src/components/list-item-icon/list-item-icon.scss
  src/components/list-item-icon/list-item-icon.tsx
  src/components/list-item-icon/readme.md
  src/components/list-item-subtitle/list-item-subtitle.scss
  src/components/list-item-subtitle/list-item-subtitle.tsx
  src/components/list-item-subtitle/readme.md
  src/components/list-item-title/list-item-title.scss
  src/components/list-item-title/list-item-title.tsx
  src/components/list-item-title/readme.md
  src/components/list-item/list-item.scss
  src/components/list-item/list-item.tsx
  src/components/list-item/readme.md
  src/components/list/list.scss
  src/components/list/list.tsx
  src/components/list/readme.md
  src/docs/essentials/colors.md
  src/index.ts
  src/scss/utilities/variables.scss
  stencil.config.dev.ts
Labels: enhancement

#124 feat(modal): add custom css attribute for modal width
  src/components/modal/modal.scss
  src/components/modal/readme.md
Labels: enhancement
