Repository baloise/design-system, pull requests merged in 2021-04, with the labels that each got.

#228 feat(checkbox): add switch style
  packages/angular/src/directives/proxies.ts
  packages/library/src/components.d.ts
  packages/library/src/components/bal-checkbox/bal-checkbox.scss
  packages/library/src/components/bal-checkbox/bal-checkbox.tsx
  packages/library/src/components/bal-checkbox/bal-switch.scss
  packages/library/src/components/bal-checkbox/index.html
  packages/library/src/components/bal-checkbox/readme.md
  packages/vue-2/src/components.ts
  packages/vue/src/components.ts
Labels: enhancement

#230 Features for Kasko
  examples/angular/src/app/form/form.component.html
  packages/library/src/components.d.ts
  packages/library/src/components/bal-card-head/bal-card-head.tsx
  packages/library/src/components/bal-card-head/readme.md
  packages/library/src/components/bal-card/index.html
  packages/library/src/components/bal-checkbox/bal-switch.scss
  packages/library/src/components/bal-field-label/bal-field-label.tsx
  packages/library/src/components/bal-field-label/readme.md
  packages/library/src/components/bal-field/bal-field.scss
  packages/library/src/components/bal-field/bal-field.tsx
  packages/library/src/components/bal-field/index.html
  packages/library/src/components/bal-field/readme.md
  packages/library/src/components/bal-hint/index.html
  packages/library/src/components/bal-notification/index.html
  packages/library/src/styles/components/card.scss
  packages/library/src/styles/elements/_all.scss
  packages/library/src/styles/elements/container.scss
  packages/library/src/styles/elements/icon.scss
  packages/library/src/styles/elements/notification.scss
Labels: enhancement

#233 feat(spinner): provide styles globally
  packages/library/src/components/bal-spinner/bal-spinner.scss
  packages/library/src/components/bal-spinner/bal-spinner.tsx
  packages/library/src/styles/elements/_all.scss
  packages/library/src/styles/elements/spinner.scss
Labels: styling

#235 feat(icon): add bal-icon-eye-closed
  packages/angular/src/directives/proxies-list.ts
  packages/angular/src/directives/proxies.ts
  packages/library/src/components.d.ts
  packages/library/src/components/bal-icon/icons/bal-icon-eye-closed.tsx
  packages/library/src/components/bal-icon/readme.md
  packages/library/src/components/bal-icon/svg/icon-eye-closed.svg
  packages/vue-2/src/components.ts
  packages/vue/src/components.ts
Labels: enhancement

#234 feat(bal-button): add name and value to button for form data
  packages/library/src/components/bal-button/bal-button.tsx
Labels: enhancement

#236 feat(button): fix loading spinner for link and outlined
  packages/library/src/components/bal-button/bal-button.tsx
  packages/library/src/components/bal-button/index.html
Labels: bug

#240 fix(select): add scrollable to dropdown-menu
  packages/angular/src/directives/proxies.ts
  packages/library/src/components.d.ts
  packages/library/src/components/bal-dropdown/bal-dropdown.tsx
  packages/library/src/components/bal-dropdown/index.html
  packages/library/src/components/bal-dropdown/readme.md
  packages/library/src/components/bal-select/bal-select.tsx
  packages/vue-2/src/components.ts
  packages/vue/src/components.ts
Labels: bug

#242 fix(IE11): add additional fixes recommended by stencil
  packages/library/stencil.config.ts
Labels: bug

#243 Feat/select v 2
  docs/package-lock.json
  docs/package.json
  docs/src/guide/tooling/validators.md
  examples/angular/src/app/form/form.component.html
  examples/angular/src/app/form/form.component.ts
  package-lock.json
  packages/angular/src/directives/proxies.ts
  packages/library/package-lock.json
  packages/library/package.json
  packages/library/src/components.d.ts
  packages/library/src/components/bal-checkbox/bal-checkbox.scss
  packages/library/src/components/bal-checkbox/bal-checkbox.tsx
  packages/library/src/components/bal-checkbox/index.html
  packages/library/src/components/bal-checkbox/readme.md
  packages/library/src/components/bal-input/readme.md
  packages/library/src/components/bal-radio/bal-radio.tsx
  packages/library/src/components/bal-radio/index.html
  packages/library/src/components/bal-radio/readme.md
  packages/library/src/components/bal-select-option/bal-select-option.scss
  packages/library/src/components/bal-select-option/bal-select-option.tsx
  packages/library/src/components/bal-select-option/bal-select-option.type.ts
  packages/library/src/components/bal-select-option/readme.md
  packages/library/src/components/bal-select/bal-select.e2e.ts
  packages/library/src/components/bal-select/bal-select.scss
  packages/library/src/components/bal-select/bal-select.tsx
  packages/library/src/components/bal-select/index.html
  packages/library/src/components/bal-select/option.utils.spec.tsx
  packages/library/src/components/bal-select/option.utils.ts
  packages/library/src/components/bal-select/readme.md
  packages/library/src/components/bal-select/value.utils.spec.tsx
  packages/library/src/components/bal-select/value.utils.ts
  packages/library/src/components/bal-tag/bal-tag.scss
  packages/library/src/components/bal-tag/bal-tag.tsx
  packages/library/src/components/bal-tag/bal-tag.vars.scss
  packages/library/src/components/bal-tag/index.html
  packages/library/src/components/bal-tag/readme.md
  packages/library/src/components/bal-text/readme.md
  packages/library/src/styles/components/dropdown.scss
  packages/library/src/styles/elements/_all.scss
  packages/library/src/styles/elements/tag.scss
  packages/library/src/styles/form/input-textarea.scss
  packages/library/src/styles/utilities/variables.scss
  packages/library/src/utils/balKeyUtil.ts
  packages/library/src/utils/index.ts
  packages/vue-2/src/components.ts
  packages/vue/src/components.ts
Labels: enhancement

#244 fix(select): fix mouse and keyboard selection
  examples/angular/package-lock.json
  examples/angular/package.json
  examples/angular/src/app/form/form.component.html
  examples/angular/src/app/form/form.component.ts
  packages/library/src/components/bal-select-option/bal-select-option.scss
  packages/library/src/components/bal-select/bal-select.tsx
  packages/library/src/components/bal-select/index.html
  packages/library/src/styles/utilities/variables.scss
Labels: bug, enhancement
