Repository baloise/design-system, pull requests merged in 2021-03, with the labels that each got.

#210 Utils
  CHANGELOG.md
  README.md
  docs/.gitignore
  docs/.scripts/copy.script.js
  docs/.scripts/tooling.script.js
  docs/src/.vuepress/config.js
  docs/src/guide/tooling/utils.md
  lerna.json
  packages/angular/README.md
  packages/library/.scripts/utils.index.js
  packages/library/.scripts/validators.index.js
  packages/library/README.md
  packages/library/package-lock.json
  packages/library/package.json
  packages/library/src/components/bal-dropdown/bal-dropdown.tsx
  packages/library/src/components/bal-input/bal-input.tsx
  packages/library/src/components/bal-navbar/bal-navbar.scss
  packages/library/src/components/bal-navbar/index.html
  packages/library/src/components/bal-navbar/readme.md
  packages/library/src/components/bal-select/bal-select.tsx
  packages/library/src/components/bal-textarea/bal-textarea.tsx
  packages/library/src/components/bal-toast/bal-toast.scss
  packages/library/src/filters/balCapitalize.ts
  packages/library/src/filters/balDefaultString.ts
  packages/library/src/filters/balFileSize.ts
  packages/library/src/filters/balJoinArray.ts
  packages/library/src/filters/balOfferNumber.ts
  packages/library/src/filters/balPhoneNumber.ts
  packages/library/src/styles/elements/table.scss
  packages/library/src/utils/balArrayUtil.spec.ts
  packages/library/src/utils/balArrayUtil.ts
  packages/library/src/utils/balDateUtil.ts
  packages/library/src/utils/balNumberUtil.spec.ts
  packages/library/src/utils/balNumberUtil.ts
  packages/library/src/utils/balStringUtil.ts
  packages/library/src/utils/balUtil.ts
  packages/library/src/utils/index.ts
  packages/library/src/validators/date.validators.ts
  packages/library/src/validators/number.validators.ts
  packages/library/src/validators/regex.validators.ts
  packages/library/src/validators/required.validators.ts
  packages/library/src/validators/string.validators.ts
  packages/testing/README.md
  packages/testing/cypress/integration/datepicker.spec.ts
  packages/testing/src/accessors/datepicker.accessor.ts
  packages/vue-2/README.md
  packages/vue/README.md
  resources/images/logo.png
Labels: documentation, enhancement, styling

#212 fix(vue): use custom elements for vue 3
  packages/vue/src/ui-library.plugin.ts
Labels: bug, enhancement

#213 Fonts
  packages/library/src/components/bal-checkbox/bal-checkbox.scss
  packages/library/src/components/bal-checkbox/bal-checkbox.tsx
  packages/library/src/components/bal-field-label/bal-field-label.tsx
  packages/library/src/components/bal-field-label/readme.md
  packages/library/src/components/bal-field-message/bal-field-message.tsx
  packages/library/src/components/bal-field-message/readme.md
  packages/library/src/components/bal-field/bal-field.scss
  packages/library/src/components/bal-radio/bal-radio.scss
  packages/library/src/components/bal-radio/bal-radio.tsx
  packages/library/src/components/bal-text/readme.md
  packages/library/src/styles/form/input-textarea.scss
  packages/library/src/styles/form/shared.scss
  packages/vue/tsconfig.json
Labels: styling

#216 Styles
  docs/src/.vuepress/components/docs-component-script.vue
  package.json
  packages/library/src/components/bal-accordion/bal-accordion.scss
  packages/library/src/components/bal-card-steps/bal-card-steps.scss
  packages/library/src/components/bal-checkbox/bal-checkbox.scss
  packages/library/src/components/bal-data/bal-data.scss
  packages/library/src/components/bal-data/index.html
  packages/library/src/components/bal-datepicker/bal-datepicker.scss
  packages/library/src/components/bal-modal/bal-modal.vars.scss
  packages/library/src/components/bal-navbar/bal-navbar.scss
  packages/library/src/components/bal-radio/bal-radio.scss
  packages/library/src/components/bal-snackbar/bal-snackbar.scss
  packages/library/src/components/bal-tabs/bal-steps.scss
  packages/library/src/components/bal-tabs/bal-tabs.scss
  packages/library/src/components/bal-timeinput/bal-timeinput.scss
  packages/library/src/components/bal-toast/bal-toast.scss
  packages/library/src/styles/components/card.scss
  packages/library/src/styles/elements/button.scss
  packages/library/src/styles/elements/title.scss
  packages/library/src/styles/form/input-textarea.scss
  packages/library/src/styles/form/shared.scss
  packages/library/src/styles/utilities/variables.scss
Labels: styling

#217 Demos
  docs/.gitignore
  docs/.scripts/examples.script.js
  docs/package.json
  docs/src/.vuepress/config.js
  docs/src/.vuepress/public/assets/images/form.png
  docs/src/.vuepress/public/assets/images/portal.png
  docs/src/guide/essentials/examples.md
  package.json
  packages/angular/src/directives/proxies-list.ts
  packages/angular/src/directives/proxies.ts
  packages/library/.gitignore
  packages/library/package.json
  packages/library/src/components.d.ts
  packages/library/src/components/bal-card-steps/bal-card-steps.tsx
  packages/library/src/components/bal-card-steps/index.html
  packages/library/src/components/bal-card-steps/readme.md
  packages/library/src/components/bal-datepicker/bal-datepicker.tsx
  packages/library/src/components/bal-datepicker/index.html
  packages/library/src/components/bal-datepicker/readme.md
  packages/library/src/components/bal-field/bal-field.scss
  packages/library/src/components/bal-icon/readme.md
  packages/library/src/components/bal-notification/bal-notification.tsx
  packages/library/src/components/bal-notification/readme.md
  packages/library/src/components/bal-radio/bal-radio.scss
  packages/library/src/components/bal-tabs/bal-steps.scss
  packages/library/src/components/bal-tabs/bal-tabs.scss
  packages/library/src/components/bal-tabs/bal-tabs.tsx
  packages/library/src/components/bal-tabs/readme.md
  packages/library/src/components/bal-teaser-step/bal-teaser-step.scss
  packages/library/src/components/bal-teaser-step/bal-teaser-step.tsx
  packages/library/src/components/bal-teaser-step/bal-teaser-step.type.ts
  packages/library/src/components/bal-teaser-step/readme.md
  packages/library/src/components/bal-teaser-steps/bal-teaser-steps.scss
  packages/library/src/components/bal-teaser-steps/bal-teaser-steps.tsx
  packages/library/src/components/bal-teaser-steps/bal-teaser-steps.vars.scss
  packages/library/src/components/bal-teaser-steps/index.html
  packages/library/src/components/bal-teaser-steps/readme.md
  packages/library/src/components/bal-text/readme.md
  packages/library/src/examples/form.html
  packages/library/src/examples/portal.html
  packages/library/src/index.ts
  packages/library/src/styles/components/card.scss
  packages/library/src/styles/elements/notification.scss
  packages/library/src/styles/elements/title.scss
  packages/library/src/styles/utilities/helpers.scss
  packages/library/stencil.examples.config.ts
  packages/vue-2/src/components.ts
  packages/vue/src/components.ts
Labels: documentation, enhancement

#218 fix(vue): only set isCustomElement function if defined in the options
  packages/vue/src/ui-library.plugin.ts
Labels: enhancement

#219 Fix/is custom element
  CHANGELOG.md
  packages/vue/src/ui-library.plugin.ts
Labels: bug

#220 feat(vue): components are globally added to the vue app instance
  packages/vue/.scripts/components.script.js
  packages/vue/.scripts/filters.script.js
  packages/vue/package-lock.json
  packages/vue/package.json
  packages/vue/rollup.config.js
  packages/vue/src/generated/components.ts
  packages/vue/src/generated/filters.ts
  packages/vue/src/ui-library.plugin.ts
Labels: enhancement

#221 Fix/vetur
  packages/vue-2/.scripts/build-vetur.js
  packages/vue-2/package-lock.json
  packages/vue-2/package.json
  packages/vue/.scripts/build-vetur.js
  packages/vue/package-lock.json
Labels: bug

#222 fix(select): add delay to clear input action
  packages/library/CHANGELOG.md
  packages/library/src/components/bal-select/bal-select.tsx
  packages/library/src/components/bal-select/index.html
Labels: bug

#223 typo
  docs/src/guide/README.md
Labels: documentation

#224 Fix/form elements
  docs/src/guide/essentials/angular.md
  docs/src/guide/essentials/vue.md
  packages/library/src/components.d.ts
  packages/library/src/components/bal-checkbox/bal-checkbox.scss
  packages/library/src/components/bal-checkbox/bal-checkbox.tsx
  packages/library/src/components/bal-checkbox/index.html
  packages/library/src/components/bal-navbar/bal-navbar.scss
  packages/library/src/components/bal-radio-group/bal-radio-group.tsx
  packages/library/src/components/bal-radio/bal-radio.scss
  packages/library/src/components/bal-radio/bal-radio.tsx
  packages/library/src/components/bal-radio/index.html
  packages/library/src/components/bal-select/bal-select.tsx
  packages/library/src/components/bal-select/index.html
  packages/library/src/components/bal-select/readme.md
  packages/library/src/helpers/helpers.ts
  packages/library/src/styles/elements/button.scss
  packages/vue/package-lock.json
  packages/vue/package.json
  packages/vue/src/helpers.ts
Labels: bug, documentation, enhancement

#225 feat(vue): add useValidator helper function
  packages/vue/src/helpers.ts
Labels: enhancement
