Repository baloise/design-system, pull requests merged in 2021-07, with the labels that each got.

#302 chore(angular): added Content Security Policy
  examples/angular/src/index.html
Labels: documentation

#307 fix react rollup config
  packages/components-react/rollup.config.js
Labels: bug

#315 Fixes 002
  CHANGELOG.md
  packages/components-angular/src/directives/proxies.ts
  packages/components-vue/src/components.ts
  packages/components/src/components.d.ts
  packages/components/src/components/bal-dropdown/bal-dropdown.tsx
  packages/components/src/components/bal-field-label/bal-field-label.tsx
  packages/components/src/components/bal-field/bal-field.scss
  packages/components/src/components/bal-field/index.html
  packages/components/src/components/bal-input/bal-input.tsx
  packages/components/src/components/bal-input/index.html
  packages/components/src/components/bal-input/readme.md
  packages/components/src/components/bal-modal/bal-modal.vars.scss
  packages/components/src/templates/spacing.html
Labels: bug, enhancement

#317 fix(text): fix bold style
  packages/components/src/components/bal-text/bal-text.scss
  packages/components/src/components/bal-text/index.html
Labels: bug

#319 fix(select): getValues returns now always an array
  examples/vue/package-lock.json
  package.json
  packages/components-vue/jest.config.js
  packages/components-vue/package-lock.json
  packages/components-vue/package.json
  packages/components-vue/src/helpers.test.ts
  packages/components-vue/src/helpers.ts
  packages/components/src/components/bal-select/utils/utils.ts
  packages/components/src/utils/balUtil.spec.ts
  packages/components/src/utils/balUtil.ts
  packages/components/src/utils/index.ts
  packages/components/src/validators/date.validator.spec.ts
  packages/components/src/validators/date.validators.ts
  packages/components/src/validators/number.validators.ts
  packages/components/src/validators/regex.validators.spec.ts
  packages/components/src/validators/regex.validators.ts
  packages/components/src/validators/required.validators.ts
  packages/components/src/validators/string.validators.spec.ts
  packages/components/src/validators/string.validators.ts
Labels: bug

#318 feat(text): add new hint color
  docs/src/design/colors.md
  packages/components/src/components.d.ts
  packages/components/src/components/bal-button/index.html
  packages/components/src/components/bal-text/bal-text.tsx
  packages/components/src/components/bal-text/index.html
  packages/components/src/components/bal-text/readme.md
  packages/components/src/styles/utilities/variables.scss
Labels: enhancement
