Repository baloise/design-system, pull requests merged in 2021-11, with the labels that each got.

#394 chore(testing): create new lock file
  package.json
  packages/testing/package-lock.json
Labels: bug, dependencies

#397 Fix/testing with filip
  package-lock.json
  package.json
  packages/components/src/components/bal-textarea/index.html
  packages/testing/cypress/integration/textarea.spec.ts
  packages/testing/cypress/support/app.ts
  packages/testing/cypress/support/pages/textarea.page.ts
  packages/testing/package-lock.json
  packages/testing/src/commands/helpers.ts
  packages/testing/src/commands/overrides/blur.command.ts
  packages/testing/src/commands/overrides/clear.command.ts
  packages/testing/src/commands/overrides/contains.command.ts
  packages/testing/src/commands/overrides/focus.command.ts
  packages/testing/src/commands/overrides/should.command.ts
  packages/testing/src/commands/overrides/type.command.ts
Labels: bug

#401 fix(heading): add missing subtile color
  packages/components/src/components/bal-heading/bal-heading.tsx
  packages/components/src/components/bal-heading/index.html
Labels: styling

#391 Add initial files and sub title to file upload
  packages/components-angular/src/directives/proxies.ts
  packages/components-vue/src/components.ts
  packages/components/src/components.d.ts
  packages/components/src/components/bal-file-upload/bal-file-upload.tsx
  packages/components/src/components/bal-file-upload/readme.md
Labels: enhancement

#404 fix(file-upload): using @baloise/web-app-utils for areArraysEqual
  packages/components/src/components/bal-file-upload/bal-file-upload.tsx
Labels: bug
