Repository baloise/design-system, pull requests merged in 2022-02, with the labels that each got.

#491 Fix/checkbox
  packages/components/src/components.d.ts
  packages/components/src/components/form/bal-checkbox/bal-checkbox-group/bal-checkbox-group.scss
  packages/components/src/components/form/bal-checkbox/bal-checkbox-group/bal-checkbox-group.tsx
  packages/components/src/components/form/bal-checkbox/bal-checkbox.scss
  packages/components/src/components/form/bal-checkbox/stories/bal-checkbox.stories.ts
  packages/components/src/components/form/bal-radio/bal-radio-group/bal-radio-group.scss
  packages/components/src/components/form/bal-radio/bal-radio-group/bal-radio-group.tsx
  packages/components/src/components/form/bal-radio/bal-radio.scss
Labels: bug, enhancement

#490 docs: add status badges
  packages/components/.storybook/main.js
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/components/form/bal-timeinput/stories/bal-timeinput.stories.ts
  packages/components/src/stories/utils/story.ts
Labels: documentation

#489 chore: make generate component global
  package.json
  packages/components/.build/stencil/generate/index.js
Labels: bug

#488 fix(accordion): add missing spacing in combination with cards
  packages/components/src/components/bal-accordion/bal-accordion.tsx
  packages/components/src/components/bal-accordion/stories/bal-accordion.stories.ts
Labels: bug, styling

#487 fix(form): add name attribute to form controls
  packages/components/src/components/form/bal-checkbox/bal-checkbox.tsx
  packages/components/src/components/form/bal-datepicker/bal-datepicker.tsx
  packages/components/src/components/form/bal-radio/bal-radio.tsx
  packages/components/src/components/form/bal-select/bal-select.tsx
  packages/components/src/components/form/bal-textarea/bal-textarea.tsx
Labels: bug

#495 Feat/vue next
  .gitignore
  package.json
  packages/components-angular/package.json
  packages/components-react/package-lock.json
  packages/components-react/package.json
  packages/components-react/rollup.config.js
  packages/components-table/package-lock.json
  packages/components-table/package.json
  packages/components-table/rollup.config.js
  packages/components-vue/.build/components.js
  packages/components-vue/package-lock.json
  packages/components-vue/package.json
  packages/components-vue/rollup.config.js
  packages/components-vue/src/plugin.ts
  packages/components/package.json
  packages/components/src/components/bal-table/stories/bal-table.stories.ts
  packages/fonts/package.json
  packages/icons/package-lock.json
  packages/icons/package.json
  packages/icons/rollup.config.js
  packages/stencil-vite-fix/package.json
  packages/testing/package-lock.json
  packages/testing/package.json
  packages/testing/rollup.config.js
  rollup.base.js
Labels: bug

#500 Fix/angular course
  packages/components/src/components/bal-list/bal-list.scss
  packages/components/src/components/bal-list/native-list.scss
  packages/components/src/components/bal-list/stories/bal-list.stories.ts
  packages/components/src/components/form/bal-input/bal-input.tsx
  packages/components/src/components/form/bal-input/stories/bal-input.docs.mdx
Labels: bug, documentation, enhancement

#499 fix(button): adjust spacing for mobile
  packages/components/src/components/bal-button/bal-button.scss
Labels: bug

#501 Fix/field hint and visual heading
  packages/components/src/components.d.ts
  packages/components/src/components/bal-heading/bal-heading.tsx
  packages/components/src/components/bal-hint/stories/bal-hint.stories.ts
  packages/components/src/components/form/bal-field/bal-field-hint/bal-field-hint.tsx
Labels: bug, enhancement

#494 feat(i18n): onBalConfigChange
  packages/components/src/config/index.ts
  packages/components/src/stories/getting-started/04-internationalization.stories.mdx
Labels: enhancement

#502 fix(i18n): fix typo in updateBalLanguage
  packages/components/src/components/form/bal-input/test/bal-input.utils.spec.ts
  packages/components/src/config/index.ts
  packages/components/src/stories/getting-started/04-internationalization.stories.mdx
Labels: bug, documentation

#503 Minor spelling
  packages/components/src/components/form/bal-field/index.html
  packages/components/src/stories/getting-started/02-testing.stories.mdx
  packages/components/src/stories/getting-started/angular/01-installation.stories.mdx
  packages/components/src/stories/getting-started/html5/01-installation.stories.mdx
  packages/components/src/stories/getting-started/react/01-installation.stories.mdx
  packages/components/src/stories/getting-started/vue/01-installation.stories.mdx
Labels: documentation

#485 Ng module
  .gitignore
  .prettierignore
  package-lock.json
  packages/components-angular/ng-package.json
  packages/components-angular/ngcc.config.js
  packages/components-angular/src/app-initialize.ts
  packages/components-angular/src/index.ts
  packages/components-angular/src/module.ts
  packages/components-angular/src/overlays/snackbar.service.ts
  packages/components-angular/src/overlays/toast.service.ts
  packages/components-react/package-lock.json
  packages/components/.build/stencil/stencil.bindings.angular.ts
  packages/components/.build/stencil/stencil.bindings.react.ts
  packages/components/.build/stencil/stencil.bindings.vue.ts
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/stories/contributors.md
  packages/components/src/stories/getting-started/angular/01-installation.stories.mdx
  packages/components/stencil.dev.config.ts
Labels: enhancement, BREAKING

#506 fix(select-button): add support for mobile devices
  packages/components/src/components.d.ts
  packages/components/src/components/form/bal-radio/bal-radio-group/bal-radio-group.scss
  packages/components/src/components/form/bal-radio/bal-radio-group/bal-radio-group.tsx
Labels: bug

#514 feat(logo): add new component
  packages/components/src/components.d.ts
  packages/components/src/components/bal-logo/bal-logo.scss
  packages/components/src/components/bal-logo/bal-logo.tsx
  packages/components/src/components/bal-logo/logos.ts
  packages/components/src/components/bal-logo/logos/baloise-group.logo.ts
  packages/components/src/components/bal-logo/logos/baloise-insurance.logo.ts
  packages/components/src/components/bal-logo/logos/baloise-soba.logo.ts
  packages/components/src/components/bal-logo/stories/bal-logo.docs.mdx
  packages/components/src/components/bal-logo/stories/bal-logo.stories.ts
  packages/components/src/components/bal-logo/stories/testing.md
  packages/components/src/components/bal-navbar/bal-navbar.scss
  packages/components/src/components/bal-navbar/stories/bal-navbar.stories.ts
  packages/components/src/styles/components/_all.scss
Labels: enhancement

#520 fix(): use utils from web-app-utils
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/components.d.ts
  packages/components/src/components/form/bal-datepicker/bal-datepicker.tsx
  packages/components/src/components/form/bal-datepicker/stories/bal-datepicker.docs.mdx
  packages/components/src/components/form/bal-datepicker/test/bal-datepicker.e2e.ts
  packages/components/src/components/form/bal-input/bal-input.utils.ts
  packages/components/src/components/form/bal-input/test/bal-input.utils.spec.ts
  packages/components/src/index.ts
  packages/components/src/utils/date.util.spec.ts
  packages/components/src/utils/date.util.ts
  packages/components/src/utils/number.util.ts
  packages/testing/package-lock.json
  packages/testing/package.json
  packages/testing/src/commands/custom/bal-datepicker.command.ts
Labels: enhancement

#517 Feat/input stepper
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/components.d.ts
  packages/components/src/components/form/bal-input-stepper/bal-input-stepper.scss
  packages/components/src/components/form/bal-input-stepper/bal-input-stepper.tsx
  packages/components/src/components/form/bal-input-stepper/bal-input-stepper.vars.scss
  packages/components/src/components/form/bal-input-stepper/stories/bal-input-stepper.docs.mdx
  packages/components/src/components/form/bal-input-stepper/stories/bal-input-stepper.stories.ts
  packages/components/src/components/form/bal-input-stepper/stories/testing.md
  packages/components/src/components/form/bal-select/bal-select-option/bal-select-option.tsx
  packages/components/src/styles/components/_all.scss
Labels: bug, enhancement

#521 Feat/header
  package-lock.json
  packages/components/src/components.d.ts
  packages/components/src/components/bal-button/bal-button.scss
  packages/components/src/components/bal-button/bal-button.tsx
  packages/components/src/components/bal-button/stories/bal-button.stories.ts
  packages/components/src/components/bal-navbar/bal-navbar-brand/bal-navbar-brand.tsx
  packages/components/src/components/bal-navbar/bal-navbar-menu-end/bal-navbar-menu-end.tsx
  packages/components/src/components/bal-navbar/bal-navbar.scss
  packages/components/src/components/bal-navbar/bal-navbar.tsx
  packages/components/src/components/bal-navbar/stories/bal-navbar.docs.mdx
  packages/components/src/components/bal-navbar/stories/bal-navbar.stories.ts
  packages/components/src/components/bal-tabs/bal-navbar-tabs.scss
  packages/components/src/components/bal-tabs/bal-tabs.scss
  packages/components/src/components/bal-tabs/bal-tabs.tsx
Labels: bug, enhancement

#522 Style/minor fixes
  packages/components/src/components.d.ts
  packages/components/src/components/bal-app/stories/bal-app.stories.tsx
  packages/components/src/components/bal-card/bal-card.scss
  packages/components/src/components/bal-heading/bal-heading.scss
  packages/components/src/components/bal-tabs/bal-o-steps.scss
  packages/components/src/components/bal-tabs/stories/bal-tabs.stories.ts
  packages/components/src/components/bal-tag/bal-tag.scss
  packages/components/src/components/bal-tag/bal-tag.tsx
  packages/components/src/components/bal-tag/stories/bal-tag.docs.mdx
  packages/components/src/components/bal-tag/stories/bal-tag.stories.ts
  packages/components/src/components/bal-tag/stories/bal-tag.templates.ts
  packages/components/src/components/form/bal-datepicker/bal-datepicker.scss
  packages/components/src/components/form/bal-field/bal-field.scss
Labels: bug, documentation, enhancement, styling
