Repository baloise/design-system, pull requests merged in 2022-04, with the labels that each got.

#570 Fix/some fixes
  packages/components/src/components.d.ts
  packages/components/src/components/bal-tabs/bal-tab.type.ts
  packages/components/src/components/bal-tabs/bal-tabs.tsx
  packages/components/src/components/bal-tabs/components/tabs.tsx
  packages/components/src/components/form/bal-select/bal-select.tsx
  packages/components/src/components/notice/bal-modal/bal-modal.scss
  packages/components/src/components/notice/bal-snackbar/bal-snackbar.scss
  packages/components/src/components/notice/bal-snackbar/bal-snackbar.tsx
  packages/testing/src/commands/custom/bal-modal.command.ts
  packages/testing/src/commands/custom/bal-modal.types.ts
  packages/testing/src/commands/helpers.ts
Labels: bug, enhancement

#577 fix: add es5 build to support no module scripts
  README.md
  packages/components/stencil.config.ts
Labels: bug

#578 fix(testing): wait until ce is ready
  packages/testing/src/commands/helpers.ts
Labels: bug

#586 Fix/adjustments
  packages/components/src/components.d.ts
  packages/components/src/components/bal-popover/bal-popover-content/bal-popover-content.tsx
  packages/components/src/components/bal-popover/bal-popover.scss
  packages/components/src/components/form/bal-checkbox/bal-checkbox.scss
  packages/components/src/components/form/bal-checkbox/bal-checkbox.tsx
  packages/components/src/components/form/bal-checkbox/stories/bal-checkbox.stories.ts
  packages/components/src/components/form/bal-datepicker/bal-datepicker.tsx
  packages/components/src/components/form/bal-datepicker/stories/bal-datepicker.stories.ts
  packages/components/src/components/form/bal-field/bal-field.tsx
  packages/components/src/components/form/bal-file-upload/bal-file-upload.tsx
  packages/components/src/components/form/bal-input-stepper/bal-input-stepper.tsx
  packages/components/src/components/form/bal-input/bal-input.tsx
  packages/components/src/components/form/bal-input/stories/bal-input.stories.ts
  packages/components/src/components/form/bal-number-input/bal-number-input.tsx
  packages/components/src/components/form/bal-number-input/stories/bal-number-input.stories.ts
  packages/components/src/components/form/bal-radio/bal-radio-group/bal-radio-group.tsx
  packages/components/src/components/form/bal-radio/bal-radio.tsx
  packages/components/src/components/form/bal-radio/stories/bal-radio.stories.ts
  packages/components/src/components/form/bal-select/bal-select.scss
  packages/components/src/components/form/bal-select/bal-select.tsx
  packages/components/src/components/form/bal-select/stories/bal-select.stories.ts
  packages/components/src/components/form/bal-slider/bal-slider.tsx
  packages/components/src/components/form/bal-slider/stories/bal-slider.stories.ts
  packages/components/src/components/form/bal-textarea/bal-textarea.tsx
  packages/components/src/components/form/bal-textarea/stories/bal-textarea.stories.ts
  packages/components/src/styles/form/input-textarea.scss
  packages/components/src/styles/form/shared.scss
Labels: bug, enhancement

#588 Fix/table tabs
  packages/components/src/components/bal-table/bal-table.scss
  packages/components/src/styles/form/input-textarea.scss
Labels: bug

#591 Feat/platforms
  .github/CODEOWNERS
  packages/components/src/components/bal-card/bal-card.scss
  packages/components/src/components/bal-card/stories/bal-card.stories.ts
  packages/components/src/config/config.ts
  packages/components/src/config/index.ts
  packages/components/src/config/initialize.ts
  packages/components/src/global.ts
  packages/components/src/index.ts
  packages/components/src/stories/design/05-breakpoints.docs.mdx
  packages/components/src/stories/utils/config.ts
  packages/components/src/utils/platform.ts
Labels: bug, enhancement

#590 Feat/number input exact number
  .github/workflows/continuous.yml
  package.json
  packages/components/src/components.d.ts
  packages/components/src/components/form/bal-number-input/bal-number-input.tsx
Labels: enhancement

#603 fix(slider): css width calculation and add ticks
  packages/components/src/components/form/bal-slider/bal-slider.tsx
Labels: bug

#606 fix(testing): set waitForComponents to optional
  packages/testing/src/commands/custom/component.command.ts
  packages/testing/src/commands/helpers.ts
Labels: bug
