Repository baloise/design-system, pull requests merged in 2022-05, with the labels that each got.

#608 Fix/vue integration
  .eslintignore
  .gitignore
  .prettierignore
  packages/components-vue/.build/components.js
  packages/components-vue/package-lock.json
  packages/components-vue/package.json
  packages/components-vue/rollup.config.js
  packages/components-vue/src/index.ts
  packages/components-vue/src/plugin.ts
  packages/components-vue/src/vue-component-lib/utils.ts
  packages/components-vue/tsconfig.json
  packages/components/.build/stencil/stencil.bindings.vue.ts
  packages/components/.storybook/vue/vue-component-lib/utils.ts
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/components/bal-app/stories/bal-app.stories.tsx
  packages/components/src/stories/contributors.md
  packages/components/src/stories/utils/args.ts
  packages/components/src/stories/utils/story.ts
  packages/components/stencil.dev.config.ts
Labels: enhancement

#612 Fix/self service
  cspell.json
  packages/components-angular/src/overlays/overlay.ts
  packages/components/.storybook/vue/vue-component-lib/utils.ts
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/components.d.ts
  packages/components/src/components/bal-button/bal-button.scss
  packages/components/src/components/form/bal-field/bal-field-label/bal-field-label.tsx
  packages/components/src/components/form/bal-field/bal-field.scss
  packages/components/src/components/form/bal-field/bal-field.tsx
  packages/components/src/components/form/bal-input/stories/bal-input.stories.ts
  packages/components/src/components/form/bal-select/bal-select.tsx
  packages/components/src/components/form/bal-select/stories/bal-select.stories.ts
  packages/components/src/components/form/bal-slider/bal-slider.tsx
  packages/components/src/components/notice/bal-modal/bal-modal.controller.ts
  packages/components/src/components/notice/bal-snackbar/index.html
  packages/components/src/components/notice/bal-toast/index.html
  packages/components/src/helpers/form-input.helpers.ts
  packages/components/src/helpers/notice.controller.ts
  packages/components/src/props.d.ts
  packages/testing/package-lock.json
  packages/testing/package.json
Labels: bug, enhancement

#614 fix(tag): add relative position on bal-card element
  packages/components-angular/package-lock.json
  packages/components-react/package-lock.json
  packages/components-table/package-lock.json
  packages/components-vue/package-lock.json
  packages/components/package-lock.json
  packages/components/src/components/bal-tag/bal-tag.scss
  packages/testing/package-lock.json
Labels: bug

#619 fix(field): add css class for messages
  packages/components/src/components/form/bal-field/bal-field.scss
Labels: bug

#620 Fix/emitted events
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/components.d.ts
  packages/components/src/components/bal-accordion/bal-accordion.tsx
  packages/components/src/components/bal-card/bal-card-subtitle/bal-card-subtitle.tsx
  packages/components/src/components/bal-heading/bal-heading.tsx
  packages/components/src/components/bal-hint/bal-hint.tsx
  packages/components/src/components/bal-icon/bal-icon.tsx
  packages/components/src/components/bal-list/bal-list-item/bal-list-item.tsx
  packages/components/src/components/bal-list/bal-list.tsx
  packages/components/src/components/bal-logo/bal-logo.tsx
  packages/components/src/components/bal-popover/bal-popover.tsx
  packages/components/src/components/bal-stage/bal-stage.tsx
  packages/components/src/components/bal-tabs/bal-tabs.tsx
  packages/components/src/components/bal-tag/bal-tag.tsx
  packages/components/src/components/bal-text/bal-text.tsx
  packages/components/src/components/form/bal-checkbox/bal-checkbox-group/bal-checkbox-group.tsx
  packages/components/src/components/form/bal-checkbox/bal-checkbox.tsx
  packages/components/src/components/form/bal-datepicker/bal-datepicker.tsx
  packages/components/src/components/form/bal-field/bal-field-message/bal-field-message.tsx
  packages/components/src/components/form/bal-input-stepper/bal-input-stepper.tsx
  packages/components/src/components/form/bal-input/bal-input.tsx
  packages/components/src/components/form/bal-number-input/bal-number-input.tsx
  packages/components/src/components/form/bal-radio/bal-radio-group/bal-radio-group.tsx
  packages/components/src/components/form/bal-radio/bal-radio.tsx
  packages/components/src/components/form/bal-select/bal-select.tsx
  packages/components/src/components/form/bal-slider/bal-slider.tsx
  packages/components/src/components/form/bal-textarea/bal-textarea.tsx
  packages/components/src/components/notice/bal-modal/bal-modal.tsx
  packages/components/src/components/notice/bal-notification/bal-notification.tsx
  packages/components/src/components/notice/bal-snackbar/bal-snackbar.tsx
  packages/components/src/components/notice/bal-toast/bal-toast.tsx
  packages/components/src/events.d.ts
  packages/components/src/stories/contributors.md
  packages/components/src/types.d.ts
Labels: bug, enhancement
