Repository baloise/design-system, pull requests merged in 2022-01, with the labels that each got.

#430 Fix/remove unsupported browser
  packages/components/.build/stencil/stencil.basic.config.ts
  packages/components/src/global.ts
  packages/components/src/stories/contributing/03-project-setup.stories.mdx
  packages/components/src/stories/migration/05-migration-from-6x-to-7x.stories.mdx
Labels: enhancement

#442 Chore/lerna
  .github/workflows/canary-release.yml
  .github/workflows/documentation.yml
  .github/workflows/release.yml
  lerna.json
  package-lock.json
  package.json
  packages/components-angular/package-lock.json
  packages/components-react/package-lock.json
  packages/components-table/package-lock.json
  packages/components-vue/package-lock.json
  packages/components/package-lock.json
  packages/components/src/components.d.ts
  packages/components/src/components/bal-footer/bal-footer.tsx
  packages/components/src/components/bal-tabs/bal-tabs.scss
  packages/components/src/components/bal-tabs/bal-tabs.tsx
  packages/components/src/components/bal-tabs/stories/bal-tabs.docs.mdx
  packages/components/src/components/bal-tabs/stories/bal-tabs.stories.ts
  packages/components/src/components/form/bal-field/bal-field.tsx
  packages/components/src/components/form/bal-input/bal-input.tsx
  packages/components/src/stories/migration/05-migration-from-6x-to-7x.stories.mdx
  packages/components/src/styles/global/_all.scss
  packages/components/src/styles/global/extends.scss
  packages/components/src/styles/utilities/_all.scss
  packages/testing/package-lock.json
Labels: bug, documentation, enhancement

#443 docs: update changelog
  .lintstagedrc
  CHANGELOG.md
  packages/components/src/stories/migration/06-migration-from-6x-to-7x.stories.mdx
  packages/components/src/stories/migration/07-migration-from-7x-to-8x.stories.mdx
Labels: documentation

#441 docs: minor text adaption of html getting started page
  packages/components/src/stories/getting-started/html5/00-overview.stories.mdx
Labels: documentation

#440 docs: fixed typos in customizing page
  packages/components/src/stories/getting-started/03-customize.stories.mdx
Labels: documentation

#436 docs: minor adaptions to icon page
  packages/components/src/stories/design/03-icons.stories.mdx
Labels: documentation

#435 docs: fixed typos and content on typography page
  packages/components/src/stories/design/02-typography.stories.mdx
Labels: documentation

#434 docs: text adaptions for page-layout
  packages/components/src/stories/design/07-page-layout.stories.mdx
Labels: documentation

#432 docs: Minor text adaptions
  packages/components/src/stories/design/05-breakpoints.docs.mdx
Labels: documentation

#433 docs: minor text adaptions
  packages/components/src/stories/design/06-grid.stories.mdx
Labels: documentation

#444 Fix/colors
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/stories/design/00-overview.stories.mdx
  packages/components/src/stories/design/01-colors.stories.mdx
  packages/components/src/stories/design/03-icons.stories.mdx
  packages/components/src/stories/design/05-breakpoints.docs.mdx
  packages/components/src/stories/design/07-page-layout.stories.mdx
  packages/components/src/styles/elements/container.scss
Labels: documentation, dependencies

#460 docs: add migration link
  CHANGELOG.md
Labels: documentation

#463 Fix/hint
  packages/components/src/components/bal-hint/bal-hint.scss
  packages/components/src/components/form/bal-datepicker/stories/bal-datepicker.docs.mdx
  packages/components/src/components/form/bal-file-upload/bal-file-upload.scss
  packages/components/src/stories/getting-started/angular/01-installation.stories.mdx
  packages/components/src/stories/getting-started/html5/01-installation.stories.mdx
  packages/components/src/stories/getting-started/react/01-installation.stories.mdx
  packages/components/src/stories/getting-started/styles/styles-fonts.md
  packages/components/src/stories/getting-started/styles/styles-sass.md
  packages/components/src/stories/getting-started/vue/01-installation.stories.mdx
Labels: bug, documentation

#466 Fix/card sub components
  packages/components/package-lock.json
  packages/components/src/components.d.ts
  packages/components/src/components/bal-accordion/stories/bal-accordion.stories.ts
  packages/components/src/components/bal-app/stories/bal-app.stories.tsx
  packages/components/src/components/bal-card/bal-card-actions/bal-card-actions.tsx
  packages/components/src/components/bal-card/bal-card-button/bal-card-button.tsx
  packages/components/src/components/bal-card/bal-card-content/bal-card-content.tsx
  packages/components/src/components/bal-card/bal-card-subtitle/bal-card-subtitle.tsx
  packages/components/src/components/bal-card/bal-card-title/bal-card-title.tsx
  packages/components/src/components/bal-card/bal-card.scss
  packages/components/src/components/bal-card/stories/bal-card.docs.mdx
  packages/components/src/components/bal-card/stories/bal-card.stories.ts
  packages/components/src/components/bal-data/stories/bal-data.stories.ts
  packages/components/src/components/bal-heading/bal-heading.scss
  packages/components/src/components/docs/bal-doc-download/bal-doc-download.tsx
  packages/components/src/components/form/bal-field/stories/bal-field.stories.ts
  packages/components/src/components/notice/bal-sheet/stories/bal-sheet.stories.ts
  packages/components/src/stories/design/templates/contact-form.template.ts
  packages/components/src/stories/design/templates/external-caluclator.template.ts
  packages/components/src/stories/design/templates/external-portal.template.ts
  packages/components/src/stories/design/templates/internal-form.template.ts
  packages/components/src/stories/design/templates/internal-wide.template.ts
  packages/components/src/stories/migration/08-migration-from-8x-to-9x.stories.mdx
Labels: bug

#467 Fix/modal
  packages/components-angular/src/helpers.ts
  packages/components-vue/src/helpers.ts
  packages/components/src/stories/getting-started/angular/03-03-usage-modal.stories.mdx
  packages/components/src/styles/elements/container.scss
Labels: bug, documentation

#468 fix(vue): add better vite support
  packages/components/.build/vite.fix.js
  packages/components/package-lock.json
  packages/components/package.json
Labels: bug

#470 fix(modal): break text in modal title
  packages/components/src/components/notice/bal-modal/bal-modal-header/bal-modal-header.tsx
  packages/components/src/components/notice/bal-modal/bal-modal.scss
Labels: bug
